### PR TITLE
Merge remote develop into LedgerHQ develop

### PR DESCRIPTION
**Pull request by bogdan-rosianu**
Merge `ElrondNetwork/ledger-elrond`'s `develop` into `LedgerHQ/app-elrond`'s `develop`
This fixes CI issues

### CODE REVIEW

**Comment by fbeutin-ledger** [comment]
Hello bogdan
Thanks for this PR fixing all the CI issues

I see that you have used the default clang formatting (not adding a customized `.clang-format` file at repo root) and that it completely changed all formatting that looked quite good before
If you want we have a standard `.clang-format` file that looks very similar to the formatting used before this PR (and the formatting used on most Ledger apps)

The choice is up to you as its your app

**Comment by bogdan-rosianu** [comment]
> 

Hello. Sure, can you point me to the `.clang-format` file? Then I'll update this PR.

**Comment by fbeutin-ledger** [comment]
This one is the most standard, it should have the least differences with the previous format

https://github.com/LedgerHQ/app-boilerplate/blob/master/.clang-format

**Comment by fbeutin-ledger** [comment]
Also could you please bump the version ? As we modify C files

**Comment by bogdan-rosianu** [comment]
> 

Tried to use the custom `.clang-format` file, but the GitHub action fails. Is there something I'm missing? Thanks
https://github.com/ElrondNetwork/ledger-elrond/pull/56

**Comment by bogdan-rosianu** [comment]
> > 
> 
> Tried to use the custom `.clang-format` file, but the GitHub action fails. Is there something I'm missing? Thanks [ElrondNetwork#56](https://github.com/ElrondNetwork/ledger-elrond/pull/56)

Figured it out. Forgot to commit the `.clang-format` file. Now it works.

**Comment by fbeutin-ledger** [comment]
I took a look at https://github.com/ElrondNetwork/ledger-elrond/pull/56/files and it looks good, I'll merge this PR once yours is merged

**Comment by bogdan-rosianu** [comment]
> I took a look at https://github.com/ElrondNetwork/ledger-elrond/pull/56/files and it looks good, I'll merge this PR once yours is merged

@fbeutin-ledger The PR was merged. Can you take a look again?

**Review by fbeutin-ledger — APPROVED** [review]

**Comment by fbeutin-ledger** [comment]
Done, thanks

**Pull request merged**
